DROP TABLE FIGHTERS;

CREATE TABLE FIGHTERS (
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(50) NOT NULL,
                          damage INT NOT NULL,
                          health INT NOT NULL,
                          resistance NUMERIC NOT NULL,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

